# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'py/path_libarr_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(336, 122)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_lineEdit = QtWidgets.QLineEdit(Form)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.horizontalLayout.addWidget(self.path_lineEdit)
        self.choose_path_btn = QtWidgets.QPushButton(Form)
        self.choose_path_btn.setObjectName("choose_path_btn")
        self.horizontalLayout.addWidget(self.choose_path_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.error_output = QtWidgets.QLabel(Form)
        self.error_output.setText("")
        self.error_output.setObjectName("error_output")
        self.verticalLayout.addWidget(self.error_output)
        self.done_btn = QtWidgets.QPushButton(Form)
        self.done_btn.setObjectName("done_btn")
        self.verticalLayout.addWidget(self.done_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Выберите путь к библиотеке libarr.so"))
        self.choose_path_btn.setText(_translate("Form", "Выбрать..."))
        self.done_btn.setText(_translate("Form", "Готово"))
