# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'py/type_c_py_lib.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(472, 136)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ctypes_rbtn = QtWidgets.QRadioButton(Form)
        self.ctypes_rbtn.setChecked(True)
        self.ctypes_rbtn.setObjectName("ctypes_rbtn")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.ctypes_rbtn)
        self.horizontalLayout.addWidget(self.ctypes_rbtn)
        self.ext_module_rbtn = QtWidgets.QRadioButton(Form)
        self.ext_module_rbtn.setObjectName("ext_module_rbtn")
        self.buttonGroup.addButton(self.ext_module_rbtn)
        self.horizontalLayout.addWidget(self.ext_module_rbtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.done_btn = QtWidgets.QPushButton(Form)
        self.done_btn.setObjectName("done_btn")
        self.verticalLayout.addWidget(self.done_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Выберете способ подключения библиотеки на СИ"))
        self.ctypes_rbtn.setText(_translate("Form", "Ctypes"))
        self.ext_module_rbtn.setText(_translate("Form", "Модуль расширения"))
        self.done_btn.setText(_translate("Form", "Готово"))
