#ifndef ERRS_H__
#define ERRS_H__


#define OK 0

#define END_INPUT_ERR 1
#define END_STOP_ERR 2
#define END_OTHER_ERR 3

#define ERR_STR_INPUT 1 * 10 + END_INPUT_ERR
#define ERR_STR_LEN 2 * 10 + END_INPUT_ERR
#define ERR_NAME_INPUT 3 * 10 + END_INPUT_ERR
#define ERR_CAPITAL_INPUT 4 * 10 + END_INPUT_ERR
#define ERR_CONTINENT_INPUT 5 * 10 + END_INPUT_ERR
#define ERR_VISE_INPUT 6 * 10 + END_INPUT_ERR
#define ERR_TIME_INPUT 7 * 10 + END_INPUT_ERR
#define ERR_COST_MIN_INPUT 8 * 10 + END_INPUT_ERR
#define ERR_TYPE_TOURISM_INPUT 9 * 10 + END_INPUT_ERR
#define ERR_COUNT_SIGHTS_INPUT 10 * 10 + END_INPUT_ERR
#define ERR_SIGHTS_INPUT 11 * 10 + END_INPUT_ERR
#define ERR_SEASON_INPUT 12 * 10 + END_INPUT_ERR
#define ERR_AIR_TEMPERATURE_INPUT 13 * 10 + END_INPUT_ERR
#define ERR_WATER_TEMPERATURE_INPUT 14 * 10 + END_INPUT_ERR
#define ERR_TYPE_SPORT_INPUT 15 * 10 + END_INPUT_ERR
#define ERR_NUM_ACT_INPUT 16 * 10 + END_INPUT_ERR

#define ERR_FILE_NOT_EXIST 1 * 10 + END_STOP_ERR
#define ERR_BAD_FILE 2 * 10 + END_STOP_ERR
#define ERR_DYNAMIC_MEMORY 3 * 10 + END_STOP_ERR

#define ERR_NO_COUNTRY_IN_TABLE 1 * 10 + END_OTHER_ERR
#define ERR_TOO_MANY_COUNTIES 2 * 10 + END_OTHER_ERR
#define ERR_WRONG_INDEX 3 * 10 + END_OTHER_ERR
#define ERR_ADD 4 * 10 + END_OTHER_ERR
#define ERR_DEL 5 * 10 + END_OTHER_ERR




/// @brief Выводит описание ошибки
/// @param [in] rc - код ошибки
void print_err(int rc);



#endif
